import type { DesignerDomainEventName } from './types'

export const DESIGNER_ACTIONS = {
  PROJECT_INIT: 'PROJECT_INIT',
  PRODUCT_SET: 'PRODUCT_SET',
  COLORS_SET: 'COLORS_SET',
  PRINT_AREA_SET: 'PRINT_AREA_SET',
  ASSET_UPLOAD_REQUEST: 'ASSET_UPLOAD_REQUEST',
  ASSET_UPLOAD_SUCCESS: 'ASSET_UPLOAD_SUCCESS',
  ASSET_UPLOAD_FAIL: 'ASSET_UPLOAD_FAIL',
  ELEMENT_ADD: 'ELEMENT_ADD',
  ELEMENT_REMOVE: 'ELEMENT_REMOVE',
  ELEMENT_SELECT: 'ELEMENT_SELECT',
  ELEMENT_TRANSFORM_START: 'ELEMENT_TRANSFORM_START',
  ELEMENT_TRANSFORM_UPDATE: 'ELEMENT_TRANSFORM_UPDATE',
  ELEMENT_TRANSFORM_END: 'ELEMENT_TRANSFORM_END',
  ELEMENT_RESET_TRANSFORM: 'ELEMENT_RESET_TRANSFORM',
  GUIDES_TOGGLE: 'GUIDES_TOGGLE',
  WARNING_ACKNOWLEDGE: 'WARNING_ACKNOWLEDGE',
  HISTORY_UNDO: 'HISTORY_UNDO',
  HISTORY_REDO: 'HISTORY_REDO',
  EXPORT_PLAN: 'EXPORT_PLAN',
  EXPORT_START: 'EXPORT_START',
  EXPORT_PROGRESS: 'EXPORT_PROGRESS',
  EXPORT_COMPLETE: 'EXPORT_COMPLETE',
  EXPORT_FAIL: 'EXPORT_FAIL',
  AUTOSAVE_SUCCESS: 'AUTOSAVE_SUCCESS',
  AUTOSAVE_RESTORE: 'AUTOSAVE_RESTORE',
} as const

export type DesignerActionName =
  (typeof DESIGNER_ACTIONS)[keyof typeof DESIGNER_ACTIONS]

export const DESIGNER_EVENT_NAMES: DesignerDomainEventName[] = [
  'DESIGNER_LOADED',
  'PRODUCT_CHANGED',
  'COLOR_SELECTION_CHANGED',
  'ASSET_UPLOADED',
  'TRANSFORM_CHANGED',
  'DPI_WARNING_RAISED',
  'OPAQUE_BG_WARNING_RAISED',
  'LOW_CONTRAST_WARNING_RAISED',
  'WARNING_RESOLVED',
  'EXPORT_STARTED',
  'EXPORT_ITEM_RENDERED',
  'EXPORT_COMPLETED',
  'EXPORT_FAILED',
  'UNDO_PERFORMED',
  'REDO_PERFORMED',
]